In [43]:
import numpy as np
import pandas as pd

np.random.seed(123)
n_trials = 100_000 #usually a high number

# 1. How likely is it that you roll doubles when rolling two dice?

In [44]:
outcomes = [1,2,3,4,5,6]
n_dice = 2

In [45]:
rolls = np.random.choice(outcomes, (n_trials, n_dice))
rolls

array([[6, 3],
       [5, 3],
       [2, 4],
       ...,
       [5, 5],
       [5, 4],
       [4, 6]])

In [46]:
doubles = rolls[:,0] == rolls[:,1]

In [47]:
doubles.sum()

16497

In [48]:
doubles.sum() / len(doubles)

0.16497

In [49]:
doubles.mean()

0.16497

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [50]:
outcomes = ['h', 't']
n_coins = 8

In [51]:
flips = np.random.choice(outcomes, (n_trials, n_coins))
flips

array([['t', 't', 't', ..., 't', 't', 'h'],
       ['h', 'h', 'h', ..., 'h', 't', 'h'],
       ['h', 'h', 't', ..., 't', 'h', 'h'],
       ...,
       ['h', 't', 'h', ..., 'h', 'h', 'h'],
       ['h', 't', 't', ..., 't', 'h', 't'],
       ['h', 't', 't', ..., 'h', 'h', 'h']], dtype='<U1')

In [52]:
heads_per_sim = (flips == 'h').sum(axis=1)
heads_per_sim

array([2, 6, 4, ..., 6, 4, 6])

In [53]:
(heads_per_sim == 3).mean()

0.22128

In [54]:
(heads_per_sim > 3).mean()

0.63372

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [57]:
outcomes = ['ds', 'wd', 'wd', 'wd']
n_billboards = 2

In [60]:
billboards = np.random.choice(outcomes, (n_trials, n_billboards))
billboards

array([['ds', 'wd'],
       ['wd', 'wd'],
       ['wd', 'wd'],
       ...,
       ['wd', 'wd'],
       ['wd', 'wd'],
       ['wd', 'ds']], dtype='<U2')

In [63]:
ds_billboards = (billboards == 'ds').sum(axis=1)
ds_billboards                


array([1, 0, 0, ..., 0, 0, 1])

In [64]:
(ds_billboards == 2).mean()

0.0611

# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [66]:
mean = 3
sd = 1.5
days = 5

In [71]:
poptarts_purchased_daily= np.random.normal(3, 1.5, (n_trials, days))
poptarts_purchased_daily

array([[ 3.962348  ,  1.45164757,  2.93284504,  1.43791589,  1.64831858],
       [ 3.88148599,  3.74193882,  2.75455715,  1.54376796,  4.12079202],
       [ 6.57506118,  0.50668804,  2.68113679,  3.73943658,  3.24462663],
       ...,
       [-1.92611912,  2.04926776,  1.81511475,  0.73564384,  1.26828257],
       [ 4.87596567,  1.79061766,  2.26956475,  4.37456785,  1.07224723],
       [ 0.88966382,  4.27061216,  4.12939172,  4.52618866,  1.48115626]])

In [73]:
poptarts_purchased_weekly = poptarts_purchased_daily.sum(axis=1)
poptarts_purchased_weekly

array([11.43307508, 16.04254193, 16.74694922, ...,  3.94218981,
       14.38296316, 15.29701263])

In [74]:
(17 - poptarts_purchased_weekly) > 1

array([ True, False, False, ...,  True,  True,  True])

In [75]:
((17 - poptarts_purchased_weekly) > 1).mean()

0.61837

# 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

### * If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [76]:
mean_men = 178
sd_men = 8

mean_women = 170
sd_women = 6

In [77]:
heights_men = np.random.normal(mean_men, sd_men, n_trials)
heights_men

array([174.23278008, 181.97632948, 182.11543645, ..., 173.59594119,
       165.6197597 , 170.405883  ])

In [79]:
heights_women = np.random.normal(mean_women, sd_women, n_trials)
heights_women

array([177.58974797, 175.65529704, 166.43884983, ..., 160.34053205,
       175.34090914, 168.45875405])

In [80]:
(heights_women > heights_men).mean()

0.21039

# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [81]:
outcomes = ['p', 'f']
probs_outcomes = [249/250, 1/250]
n_students = 50

In [82]:
installs = np.random.choice(outcomes, (n_trials, n_students),
                 p = probs_outcomes)
installs

array([['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ...,
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p']], dtype='<U1')

In [83]:
total_fails =(installs == 'f').sum(axis=1)
total_fails

array([0, 0, 3, ..., 0, 0, 0])

In [84]:
(total_fails == 0).mean()

0.81891

### * 100 students? 

In [85]:
n_students = 100

installs = np.random.choice(outcomes, (n_trials, n_students),
                 p = probs_outcomes)

total_fails =(installs == 'f').sum(axis=1)

(total_fails == 0).mean()

0.67117

### * What is the probability that we observe an installation issue within the first 150 students that download anaconda?


In [86]:
n_students = 150

installs = np.random.choice(outcomes, (n_trials, n_students),
                 p = probs_outcomes)

total_fails =(installs == 'f').sum(axis=1)

(total_fails > 0).mean()

0.45273

### * How likely is it that 450 students all download anaconda without an issue?

In [87]:
n_students = 450

installs = np.random.choice(outcomes, (n_trials, n_students),
                 p = probs_outcomes)

total_fails =(installs == 'f').sum(axis=1)

(total_fails == 0).mean()

0.16378

# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [88]:
p_truck = 0.7
n_days = 3

In [90]:
is_truck_question = np.random.random((n_trials, n_days))
is_truck_question

array([[0.46618031, 0.78507888, 0.81968266],
       [0.47537143, 0.65984111, 0.50098539],
       [0.52480561, 0.62403107, 0.13200522],
       ...,
       [0.82926584, 0.45016315, 0.72644359],
       [0.95957348, 0.39574926, 0.48442953],
       [0.43635868, 0.1615422 , 0.22489574]])

In [92]:
yes_truck = is_truck_question < p_truck
yes_truck

array([[ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       ...,
       [False,  True, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [98]:
(yes_truck.sum(axis=1) == 0).mean()

0.02796

### * How likely is it that a food truck will show up sometime this week?

In [97]:
n_days = 5

In [113]:
is_truck_question = np.random.random((n_trials, n_days))

yes_truck = is_truck_question < p_truck

#update to show at least one truck shows up this week
(yes_truck.sum(axis=1) >= 1).mean()

0.99751

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [100]:
n_people = 23
outcomes = list(range(1,366))

In [105]:
birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays

array([[196, 267,   3, ..., 260,  17, 269],
       [ 65, 233,  57, ..., 260,  53,  74],
       [363, 208, 231, ..., 214, 190, 316],
       ...,
       [137,  30, 352, ..., 319, 216, 218],
       [106,   8, 266, ..., 352, 243, 128],
       [271, 331,  18, ...,  65, 246, 159]])

In [106]:
birthdays = pd.DataFrame(birthdays)
birthdays

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      196  267    3  264  218  289  216   58  277   42  ...  173    6   43   
1       65  233   57  343  239  257  336  299   44  296  ...  110   16   25   
2      363  208  231  267  250  170   93  165  204  351  ...   32  208  216   
3      176  117  341  357  285  218   55  343   68  360  ...  109  101   63   
4       21   69  323  135  337  364  104  141  241  221  ...  247  180  112   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995   37   63   73  152  345   85  139  322   28  119  ...  357  305  212   
99996   84  342  252   74  297   58  283  361   62  252  ...  201  239   96   
99997  137   30  352  128  313  223  218  295    6  122  ...  263  264   13   
99998  106    8  266  311  162   87  238   29    5  272  ...   99  100  243   
99999  271  331   18   70  288  206  185  261  135   15  ...  115   56  350   

        16   17   18   19   20   21   22  
0      300  340  350  174  260   17  269  
1      284   19  265  347  260   53   74  
2      309  334   45  351  214  190  316  
3        1  127    8  161  324  185  201  
4      271   95  194  280  174   88  246  
...    ...  ...  ...  ...  ...  ...  ...  
99995  259  114  303  288   45  258   18  
99996   22  185   40  165  232  149   53  
99997  195  182  242   30  319  216  218  
99998  259  182  224   70  352  243  128  
99999  358  356   76  301   65  246  159  

[100000 rows x 23 columns]

In [107]:
birthdays.nunique(axis=1)

0        23
1        22
2        21
3        23
4        23
         ..
99995    23
99996    22
99997    21
99998    22
99999    23
Length: 100000, dtype: int64

In [109]:
(birthdays.nunique(axis=1) < n_people).mean()

0.51092

### * 20 people?

In [110]:
n_people = 20

birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays = pd.DataFrame(birthdays)

(birthdays.nunique(axis=1) < n_people).mean()

0.41325

### * 40 people?

In [112]:
n_people = 40

birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays = pd.DataFrame(birthdays)

(birthdays.nunique(axis=1) < n_people).mean()

0.88958